workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "org.bettingbuddy.app"
    scripts:
      - name: Install dependencies
        script: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3-pip python3-venv zip unzip
          pip3 install --upgrade pip
          pip3 install buildozer cython virtualenv
          sudo apt install -y openjdk-17-jdk

      - name: Initialize Buildozer
        script: |
          mkdir -p $CM_BUILD_DIR/bettingbuddy
          cd $CM_BUILD_DIR/bettingbuddy
          cp -r $CM_SOURCE/* .
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi

      - name: Build APK
        script: |
          cd $CM_BUILD_DIR/bettingbuddy
          buildozer -v android debug

    artifacts:
      - $CM_BUILD_DIR/bettingbuddy/bin/*.apk
      - $CM_BUILD_DIR/bettingbuddy/bin/*.aab
    publishing:
      email:
        recipients:
          - gianison.boekhoudt@icloud.com

