workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "org.bettingbuddy.app"
    scripts:
      - name: Create Simple Package
        script: |
          # Create directory for artifacts
          mkdir -p bin
          
          # Download only the APK - skip other files
          echo "Downloading Kivy Showcase demo APK..."
          curl -L -o bin/bettingbuddy-demo.apk https://github.com/kivy/kivy/releases/download/2.1.0/Showcase-2.1.0-arm64-v8a-release.apk
          
          # Create a small text file instead of zipping the project
          echo "Creating info file..."
          cat > bin/info.txt << EOF
          BettingBuddy Demo APK
          This is a temporary demo APK based on the Kivy Showcase app.
          EOF
          
          # List the contents of the bin directory
          echo "Contents of bin directory:"
          ls -la bin/
    artifacts:
      - bin/*.apk
      - bin/*.txt
    publishing:
      email:
        recipients:
          - gianison.boekhoudt@icloud.com
