workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "org.bettingbuddy.app"
    scripts:
      - name: Install dependencies
        script: |
          # Installeer Homebrew en afhankelijkheden
          brew install python@3.10 openjdk@17 pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer

          # Maak en activeer een virtuele omgeving
          python3 -m venv venv
          source venv/bin/activate

          # Upgrade pip en installeer de Buildozer dependencies binnen de virtuele omgeving
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython virtualenv

          echo "Virtuele omgeving geactiveerd en Buildozer geïnstalleerd."

      - name: Initialize Buildozer
        script: |
          source venv/bin/activate  # Zorg ervoor dat de virtuele omgeving actief is
          mkdir -p $CM_BUILD_DIR/bettingbuddy
          cd $CM_BUILD_DIR/bettingbuddy
          cp -r $CM_SOURCE/* .
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi

      - name: Build APK
        script: |
          source venv/bin/activate  # Zorg ervoor dat de virtuele omgeving actief is
          cd $CM_BUILD_DIR/bettingbuddy
          buildozer -v android debug

    artifacts:
      - $CM_BUILD_DIR/bettingbuddy/bin/*.apk
      - $CM_BUILD_DIR/bettingbuddy/bin/*.aab
    publishing:
      email:
        recipients:
          - gianison.boekhoudt@icloud.com

