workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "org.bettingbuddy.app"
    scripts:
      - name: Install dependencies
        script: |
          # Update Homebrew en installeer de vereiste packages
          brew update
          brew install python@3.10 openjdk@17
          brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer

          # Zorg ervoor dat we de juiste Python-versie gebruiken
          echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc
          source ~/.zshrc

          # Upgrade pip en installeer de Python-pakketten
          pip3 install --upgrade pip setuptools wheel
          pip3 install buildozer cython virtualenv

      - name: Initialize Buildozer
        script: |
          # Maak alleen de map en kopieer noodzakelijke bestanden
          mkdir -p $CM_BUILD_DIR/bettingbuddy
          cd $CM_BUILD_DIR/bettingbuddy
          cp -r $CM_SOURCE/buildozer.spec .  # Alleen buildozer.spec kopiëren
          cp -r $CM_SOURCE/src/* .  # Kopieer enkel de benodigde bestanden uit je source folder

          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi

      - name: Build APK
        script: |
          cd $CM_BUILD_DIR/bettingbuddy
          buildozer -v android debug

    artifacts:
      - $CM_BUILD_DIR/bettingbuddy/bin/*.apk
      - $CM_BUILD_DIR/bettingbuddy/bin/*.aab
    publishing:
      email:
        recipients:
          - gianison.boekhoudt@icloud.com

