workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "org.bettingbuddy.app"
    scripts:
      - name: Set Python version and install dependencies
        script: |
          brew install pyenv
          pyenv install 3.9.13
          pyenv global 3.9.13
          python --version
          pip3 install --upgrade pip
          pip3 install setuptools wheel
          pip3 install buildozer==1.5.0
          pip3 install cython==0.29.33
          brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer
      - name: Build Android APK
        script: |
          buildozer android debug
    artifacts:
      - bin/*.apk
    publishing:
      email:
        recipients:
          - gianison.boekhoudt@icloud.com
