workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "org.bettingbuddy.app"
    scripts:
      - name: Set up Python environment
        script: |
          pip3 install --upgrade pip
          pip3 install --upgrade setuptools wheel
          pip3 install --upgrade buildozer==1.5.0  # Use specific version
          pip3 install --upgrade cython pillow
          pip3 install cairosvg  # For SVG support

      - name: Set up Android SDK
        script: |
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          # Check NDK and SDK directories
          ls -la $ANDROID_SDK_ROOT || echo "SDK not found"
          ls -la $ANDROID_NDK_HOME || echo "NDK not found"
          
      - name: Clean previous build
        script: |
          rm -rf .buildozer || true
          rm -rf bin || true
          
      - name: Build Android APK
        script: |
          # Set environment variables
          export P4A_IGNORE_DEPENDENCIES=1
          export PYTHONPATH=$PYTHONPATH:$PWD
          
          # Make buildozer spec changes directly
          echo "Updating buildozer.spec..."
          sed -i'.bak' 's/^android.arch =.*/android.arch = arm64-v8a/' buildozer.spec
          sed -i'.bak' 's/^p4a.branch =.*/p4a.branch = develop/' buildozer.spec
          sed -i'.bak' 's/^android.api =.*/android.api = 33/' buildozer.spec
          sed -i'.bak' 's/^android.sdk =.*/android.sdk = 33/' buildozer.spec
          sed -i'.bak' 's/^requirements =.*/requirements = python3,kivy==2.1.0,kivymd==1.1.1,requests,pillow==9.5.0,plyer,sqlite3,datetime,cairosvg/' buildozer.spec
          
          # Install required dependencies
          echo "Installing Python dependencies..."
          pip install --upgrade pip wheel setuptools
          pip install cython==0.29.33 buildozer==1.5.0
          pip install kivy==2.1.0 kivymd==1.1.1
          pip install pillow==9.5.0 cairosvg
          
          # Show installed packages
          echo "Installed pip packages:"
          pip list
          
          # Run buildozer with more verbose output
          echo "Running buildozer..."
          python -m buildozer android debug -v
          
          # Show output files
          echo "APK build complete. Files in bin directory:"
          ls -la bin/
    artifacts:
      - bin/*.apk
      - $HOME/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/bettingbuddy/build/outputs/apk/debug/*.apk
  
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "org.bettingbuddy.app"
        XCODE_WORKSPACE: "ios/BettingBuddy.xcworkspace"
        XCODE_SCHEME: "BettingBuddy"
    scripts:
      - name: Set up Python environment
        script: |
          pip3 install --upgrade pip
          pip3 install --upgrade kivy-ios
      # Further iOS scripts would go here
      - name: Build iOS (Simulated - not fully implemented)
        script: |
          echo "iOS build is not yet fully implemented"
    artifacts:
      - ios/build/Release-iphoneos/*.ipa
