workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "org.bettingbuddy"  # Match this with your buildozer.spec
    scripts:
      - name: Check available disk space
        script: df -h

      - name: Cleanup old build files
        script: |
          echo "Cleaning up old build files..."
          rm -rf $HOME/.buildozer
          rm -rf $CM_BUILD_DIR/bettingbuddy/.buildozer
          echo "Cleanup completed."

      - name: Install dependencies
        script: |
          echo "Installing dependencies..."
          brew install python@3.10 openjdk@17 pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer

          echo "Creating and activating virtual environment..."
          python3 -m venv venv
          source venv/bin/activate

          echo "Updating pip and installing Buildozer..."
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython virtualenv

          echo "Setup completed!"

      - name: Prepare Build Directory
        script: |
          source venv/bin/activate
          mkdir -p $CM_BUILD_DIR/bettingbuddy
          echo "Copying project files to build directory..."
          
          # Copy only necessary files to save space
          rsync -av --exclude='bin' --exclude='__pycache__' --exclude='.git' $CM_SOURCE/ $CM_BUILD_DIR/bettingbuddy/
          
          cd $CM_BUILD_DIR/bettingbuddy
          
          # Check if main.py exists
          if [ ! -f "main.py" ]; then
            echo "WARNING: main.py not found in project root!"
            ls -la  # List files to debug
          fi
          
          echo "Using existing buildozer.spec file..."

      - name: Build APK
        script: |
          source venv/bin/activate
          cd $CM_BUILD_DIR/bettingbuddy
          echo "Starting Buildozer Android build..."

          # Display Buildozer version
          buildozer --version
          
          # Explicitly clean before building to ensure fresh start
          buildozer android clean
          
          # Build the APK in verbose mode
          buildozer -v android debug
          
          # List generated APK files
          echo "Generated APK files:"
          ls -la bin/

    artifacts:
      - $CM_BUILD_DIR/bettingbuddy/bin/*.apk
    publishing:
      email:
        recipients:
          - gianison.boekhoudt@icloud.com
