workflows:
  android-workflow:  # Dit is nu de naam die Codemagic verwacht
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "org.bettingbuddy.app"
    scripts:
      - name: Install dependencies
        script: |
          # Installeer Homebrew (indien nog niet geïnstalleerd)
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

          # Installeer de benodigde dependencies via Homebrew
          brew install python@3.10
          brew install openjdk@17

          # Upgrade pip en installeer de benodigde Python-pakketten
          pip3 install --upgrade pip
          pip3 install buildozer cython virtualenv

      - name: Initialize Buildozer
        script: |
          mkdir -p $CM_BUILD_DIR/bettingbuddy
          cd $CM_BUILD_DIR/bettingbuddy
          cp -r $CM_SOURCE/* .
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi

      - name: Build APK
        script: |
          cd $CM_BUILD_DIR/bettingbuddy
          buildozer -v android debug

    artifacts:
      - $CM_BUILD_DIR/bettingbuddy/bin/*.apk
      - $CM_BUILD_DIR/bettingbuddy/bin/*.aab
    publishing:
      email:
        recipients:
          - gianison.boekhoudt@icloud.com

